version: "3.8"

services:
  actions-runner:
    image: myoung34/github-runner:ubuntu-noble
    restart: always
    environment:
      RUNNER_NAME: swarm-aarch64
      RUNNER_SCOPE: org
      ORG_NAME: cssnr
      ACCESS_TOKEN: "${GH_PAT}"
      RUNNER_WORKDIR: /_work
      #RUNNER_GROUP: my-group
      #LABELS: my-label,other-label
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 500M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/actions-runners:/_work
