version: "3.8"

services:
  actions-runner:
    image: myoung34/github-runner:${VERSION:-latest}
    restart: always
    environment:
      RUNNER_NAME: swarm-aarch64
      RUNNER_SCOPE: org
      ORG_NAME: cssnr
      APP_ID: 1162137
      APP_PRIVATE_KEY: ${APP_PRIVATE_KEY}
      #ACCESS_TOKEN: ${GH_PAT}
      RUNNER_WORKDIR: /_work
      DEBUG_OUTPUT: "true"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 500M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/actions-runners:/_work
