name: "Deploy"

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to Deploy"
        default: "latest"
        required: true

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Portainer Deploy"
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          name: actions-runner-cssnr
          file: swarm-aarch64.yaml
          type: file
          url: ${{ secrets.PORTAINER_URL }}
          token: ${{ secrets.PORTAINER_TOKEN }}
          env_json: '{"APP_PRIVATE_KEY": "${{ secrets.ACTIONS_RUNNER_APP_KEY }}", "VERSION": ${{ inputs.VERSION }}'
